# CodeRabbit configuration for instaPro backend
# Docs: https://docs.coderabbit.ai/configuration/

language: en-US

reviews:
  profile: assertive
  auto_review:
    enabled: true
    drafts: false
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  path_instructions:
    - path: "prisma/migrations/**"
      instructions: |
        Review migrations for PostgreSQL safety:
        - Will this migration lock a large table? Flag any ALTER TABLE on tables with >100k rows.
        - Is the migration backwards-compatible with the currently deployed application?
        - Are new columns nullable or have defaults? Required columns on existing tables will break inserts.
        - Are indexes created CONCURRENTLY where appropriate?
        - Check for potential downtime risks (table rewrites, exclusive locks).
        - Verify both main and demo databases will migrate correctly.

    - path: "prisma/schema.prisma"
      instructions: |
        Check schema changes for:
        - Proper relation definitions (foreign keys, cascade rules).
        - Consistent naming conventions (camelCase fields, PascalCase models).
        - Required fields have sensible defaults or are nullable for existing data.
        - Soft delete pattern: models that need it should have a `deletedAt DateTime?` field.

    - path: "src/modules/**/controllers/**"
      instructions: |
        Verify controllers follow project conventions:
        - `@AuthRoleGuard()` at class level for authentication.
        - `@CheckRole()` for authorization where needed.
        - `@CurrentAccountId()` to extract accountId — never trust client-sent account IDs.
        - `@TransformDto` for response transformation.
        - Swagger decorators for API documentation.
        - Controllers must be thin — no business logic, delegate to services.

    - path: "src/modules/**/services/**"
      instructions: |
        Verify services follow project conventions:
        - Extend `BaseService<TRepository>` for standard CRUD.
        - Validate accountId ownership before mutations.
        - Use NestJS exceptions (NotFoundException, BadRequestException, etc.).
        - Multi-table writes wrapped in `prisma.$transaction()`.
        - No direct Prisma client calls — use repository methods.

    - path: "src/modules/**/repositories/**"
      instructions: |
        Verify repositories follow project conventions:
        - Extend `BaseRepository` with proper generic types.
        - All queries scoped by `accountId` in where clauses.
        - Use base class helpers (_create, _findUnique, _update, _delete, _findWithPagination).
        - Soft-deletable models filter `deletedAt: null`.

    - path: "src/modules/**/dtos/**"
      instructions: |
        Verify DTOs follow project conventions:
        - All input fields have `class-validator` decorators.
        - GraphQL support via `@InputType()` and `@Field()`.
        - Response DTOs use `class-transformer` (@Exclude, @Expose).
        - Create/Update/Response DTOs in separate files.

    - path: "src/core/**"
      instructions: |
        Core infrastructure changes need extra scrutiny:
        - Changes here affect every module. Verify backwards compatibility.
        - Check that existing module contracts are preserved.
        - Ensure auth/authorization changes don't create security gaps.

    - path: "**/*.spec.ts"
      instructions: |
        Review tests for:
        - Meaningful assertions (not just "it doesn't throw").
        - Edge cases and error paths covered.
        - No hardcoded magic values — use @faker-js/faker.
        - Proper cleanup in afterEach/afterAll.

    - path: ".github/workflows/**"
      instructions: |
        Review CI changes for:
        - No `|| true` on test/lint/typecheck steps (must fail the build).
        - Secrets not leaked in logs.
        - Proper caching and artifact handling.

chat:
  auto_reply: true

early_access: true
